version: '3'

services:
  # Database
  db:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: triandamai
      MYSQL_DATABASE: db_inventory
      MYSQL_USER: trian
      MYSQL_PASSWORD: triandamai
    ports:
      - '3306:3306'
    networks:
      - inventory_network
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: triandamai
    networks:
      - inventory_network
networks:
  inventory_network:
volumes:
  db_data: